import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const styleRoot = path.join(root, "src/features/desktop-agent/ui/styles");
const css = [
  fs.readFileSync(path.join(root, "src/features/desktop-agent/ui/desktop-agent.css"), "utf8"),
  ...["foundation.css", "transcript.css", "activities.css", "tool-results.css", "blocking.css", "composer.css", "pickers.css", "responsive.css"]
    .map((file) => fs.readFileSync(path.join(styleRoot, file), "utf8")),
].join("\n");
const composer = fs.readFileSync(path.join(root, "src/features/desktop-agent/ui/AgentComposer.tsx"), "utf8");
const composerToolbar = fs.readFileSync(path.join(root, "src/features/desktop-agent/ui/composer/AgentComposerToolbar.tsx"), "utf8");
const attachmentButton = fs.readFileSync(path.join(root, "src/features/desktop-agent/ui/composer/AgentAttachmentButton.tsx"), "utf8");
const panel = fs.readFileSync(path.join(root, "src/features/desktop-agent/ui/AgentChatTabPanel.tsx"), "utf8");
const picker = fs.readFileSync(path.join(root, "src/features/desktop-agent/ui/AgentPickerPopover.tsx"), "utf8");
const brandMark = fs.readFileSync(path.join(root, "src/features/desktop-agent/ui/AgentBrandMark.tsx"), "utf8");
const messagePart = fs.readFileSync(path.join(root, "src/features/desktop-agent/ui/AgentMessagePart.tsx"), "utf8");
const transcript = fs.readFileSync(path.join(root, "src/features/desktop-agent/ui/AgentTranscript.tsx"), "utf8");
const commandActivity = fs.readFileSync(path.join(root, "src/features/desktop-agent/ui/activity/AgentCommandActivity.tsx"), "utf8");
const fileQueryActivity = fs.readFileSync(path.join(root, "src/features/desktop-agent/ui/activity/AgentFileQueryActivity.tsx"), "utf8");
const evidenceTree = fs.readFileSync(path.join(root, "src/features/desktop-agent/ui/activity/AgentToolEvidenceTree.tsx"), "utf8");
const evidenceModel = fs.readFileSync(path.join(root, "src/features/desktop-agent/domain/agent-tool-evidence.ts"), "utf8");
const safeMarkdown = fs.readFileSync(path.join(root, "src/features/desktop-agent/ui/SafeMarkdown.tsx"), "utf8");
const panelStatus = fs.readFileSync(path.join(root, "src/features/desktop-agent/ui/AgentPanelStatus.tsx"), "utf8");
const dataSidebarCss = fs.readFileSync(path.join(root, "src/features/data-workspace/data-shell.css"), "utf8");
const tokensCss = fs.readFileSync(path.join(root, "src/styles/tokens.css"), "utf8");
const menuCss = fs.readFileSync(path.join(root, "src/styles/menus.css"), "utf8");
const layoutCss = fs.readFileSync(path.join(root, "src/styles/layout.css"), "utf8");
const responsiveCss = fs.readFileSync(path.join(styleRoot, "responsive.css"), "utf8");

describe("Desktop Agent Cursor-style sidebar visual contract", () => {
  it("keeps user prompts as full-width rows and Agent replies in document flow", () => {
    expect(css).toMatch(/--agent-inline-inset:\s*var\(--desktop-sidebar-row-left-gap, 12px\)/);
    expect(css).toMatch(/--agent-dock-padding-top:\s*12px/);
    expect(css).toMatch(/--agent-dock-padding-bottom:\s*12px/);
    expect(css).toMatch(/--agent-control-size:\s*30px/);
    expect(css).toMatch(/--agent-message-content-inset:\s*12px/);
    expect(css).toMatch(/--agent-message-turn-gap:\s*24px/);
    expect(css).toMatch(/--agent-work-handoff-gap:\s*8px/);
    expect(css).toMatch(/--agent-radius-composer:\s*10px/);
    expect(css).toMatch(/--agent-radius-message:\s*var\(--agent-radius-composer\)/);
    expect(css).toMatch(/\.desktop-agent-transcript\s*\{[^}]*padding:\s*12px var\(--agent-inline-inset\) 24px/s);
    expect(css).toMatch(/\.desktop-agent-live-tail\s*\{[^}]*gap:\s*var\(--agent-message-turn-gap\)[^}]*padding:\s*0 0 20px/s);
    expect(css).toMatch(/--agent-user-message-surface:\s*color-mix\(in srgb, var\(--agent-composer-surface\) 48%, var\(--agent-canvas\)\)/);
    expect(css).toMatch(/\.desktop-agent-message\.is-user\s*\{[^}]*box-sizing:\s*border-box[^}]*width:\s*100%[^}]*max-width:\s*none[^}]*margin:\s*0[^}]*padding:\s*8px var\(--agent-message-content-inset\)[^}]*border:\s*1px solid var\(--agent-border-subtle\)[^}]*background:\s*var\(--agent-user-message-surface\)[^}]*box-shadow:\s*none/s);
    expect(css).toMatch(/\.desktop-agent-virtual-row\s*\{[^}]*padding-bottom:\s*2px/s);
    expect(css).toMatch(/\.desktop-agent-virtual-row\[data-kind="user"\]\s*\{[^}]*padding-bottom:\s*var\(--agent-message-turn-gap\)/s);
    expect(css).toMatch(/\.desktop-agent-virtual-row\[data-kind="assistant"\]\s*\{[^}]*padding:\s*2px 0 var\(--agent-work-handoff-gap\)/s);
    expect(css).toMatch(/\.desktop-agent-virtual-row\[data-kind="turn-summary"\]\s*\{[^}]*padding:\s*0 0 var\(--agent-work-handoff-gap\)/s);
    expect(css).toMatch(/\.desktop-agent-virtual-row:not\(\[data-kind="user"\]\):has\(\+ \.desktop-agent-virtual-row\[data-kind="user"\]\)\s*\{[^}]*padding-bottom:\s*var\(--agent-message-turn-gap\)/s);
    expect(css).toMatch(/\.desktop-agent-virtual-row\[data-kind="tool"\],[^{]*\[data-kind="command"\],[^{]*\[data-kind="file-change"\]\s*\{[^}]*padding-bottom:\s*0/s);
    expect(css).toMatch(/\.desktop-agent-tool-row\s*\{[^}]*min-height:\s*30px[^}]*grid-template-columns:\s*auto auto minmax\(0, 1fr\) auto[^}]*padding:\s*0 4px/s);
    expect(css).toMatch(/\.desktop-agent-tool-call\.has-detail \.desktop-agent-tool-row\s*\{[^}]*grid-template-columns:\s*auto auto auto minmax\(0, 1fr\) auto/s);
    expect(css).toMatch(/\.desktop-agent-notice\.is-connection\s*\{[^}]*border:\s*1px solid var\(--agent-border-subtle\)[^}]*border-radius:\s*var\(--agent-radius-message\)[^}]*background:\s*var\(--agent-composer-surface\)[^}]*color:\s*var\(--agent-text-muted\)/s);
    expect(css).toMatch(/\.desktop-agent-message\.is-assistant\s*\{[^}]*box-sizing:\s*border-box[^}]*width:\s*100%[^}]*padding:\s*0 var\(--agent-message-content-inset\)[^}]*border:\s*0[^}]*background:\s*transparent[^}]*box-shadow:\s*none/s);
    expect(css).not.toContain(".desktop-agent-message-actions");
    expect(messagePart).not.toContain("Copy response");
    expect(messagePart).not.toContain("clipboard");
    expect(css).toMatch(/\.desktop-agent-message-text\s*\{[^}]*font-size:\s*var\(--agent-font-size\)/s);
    expect(css).toMatch(/\.desktop-agent-markdown\s*\{[^}]*font-size:\s*var\(--agent-font-size\)[^}]*line-height:\s*1\.66/s);
    expect(messagePart).toContain('data-message-surface={isAssistant ? "document" : "row"}');
    expect(css).toMatch(/\.desktop-agent-turn-summary\s*\{[^}]*padding-inline:\s*var\(--agent-message-content-inset\)[^}]*color:\s*var\(--agent-text-subtle\)[^}]*font-size:\s*var\(--agent-font-size\)[^}]*line-height:\s*1\.66[^}]*text-align:\s*start/s);
    expect(css).not.toContain("desktop-agent-turn-summary-line");
    expect(responsiveCss).not.toMatch(/desktop-agent-virtual-row\[data-kind="assistant"\]/);
    expect(responsiveCss).not.toMatch(/desktop-agent-message\.is-(?:assistant|user)/);
    expect(responsiveCss).not.toMatch(/desktop-agent-turn-summary/);
    expect(transcript).toContain('kind: "turn-summary"');
    expect(transcript).not.toContain("style={{");
    expect(transcript).toContain("agentVirtualCanvasGeometry(layout.totalHeight)");
    expect(transcript).toContain("agentVirtualRowGeometry(top)");
  });

  it("keeps chrome in flow and gives the composer explicit control sizing", () => {
    expect(css).toMatch(/\.desktop-agent-header-region\s*\{[^}]*height:\s*var\(--desktop-sidebar-navigation-height\)/s);
    expect(css).toMatch(/\.desktop-agent-header-region\s*\{[^}]*--desktop-sidebar-control-size:\s*26px[^}]*--desktop-sidebar-navigation-height:\s*var\(--desktop-chrome-height\)[^}]*--desktop-sidebar-navigation-padding-outer:\s*6px[^}]*--desktop-sidebar-navigation-padding-inner:\s*6px/s);
    expect(css).not.toMatch(/\.desktop-agent-header-region\s*\{[^}]*box-shadow:/s);
    expect(tokensCss).toMatch(/--desktop-sidebar-navigation-padding-outer:\s*12px/);
    expect(tokensCss).toMatch(/--desktop-sidebar-navigation-padding-inline:\s*12px/);
    expect(tokensCss).toMatch(/--desktop-sidebar-navigation-padding-inner:\s*4px/);
    expect(dataSidebarCss).toMatch(/\.desktop-sidebar-navigation-surface\[data-placement="top"\]\s*\{[^}]*padding:\s*var\(--desktop-sidebar-navigation-padding-outer\)\s*var\(--desktop-sidebar-navigation-padding-inline\)\s*var\(--desktop-sidebar-navigation-padding-inner\)/s);
    expect(css).toMatch(/\.desktop-agent-session-header\s*\{[^}]*width:\s*100%[^}]*height:\s*var\(--desktop-sidebar-navigation-height\)[^}]*justify-content:\s*flex-start[^}]*padding:\s*var\(--desktop-sidebar-navigation-padding-outer\)\s*var\(--desktop-sidebar-navigation-padding-inline\)\s*var\(--desktop-sidebar-navigation-padding-inner\)[^}]*border:\s*0/s);
    expect(css).toMatch(/\.desktop-agent-session-identity\s*\{[^}]*max-width:\s*calc\([^}]*100%[^}]*- var\(--desktop-sidebar-control-size\)[^}]*- var\(--desktop-sidebar-control-size\)[^}]*- var\(--desktop-sidebar-nav-gap\)[^}]*- var\(--desktop-sidebar-nav-gap\)[^}]*\)[^}]*flex:\s*0 1 auto/s);
    expect(css).toMatch(/\.desktop-agent-session-agent-selector\s*\{[^}]*width:\s*max-content[^}]*max-width:\s*100%/s);
    expect(css).toMatch(/\.desktop-agent-session-header-actions\s*\{[^}]*gap:\s*var\(--desktop-sidebar-nav-gap\)/s);
    expect(css).toMatch(/\.desktop-agent-icon-button\s*\{[^}]*width:\s*var\(--desktop-sidebar-control-size\)[^}]*height:\s*var\(--desktop-sidebar-control-size\)/s);
    expect(css).toMatch(/\.desktop-agent-transcript-wrap::before\s*\{[^}]*inset-inline:\s*0 var\(--desktop-sidebar-navigation-fade-scrollbar-inset\)[^}]*height:\s*calc\(var\(--desktop-sidebar-navigation-fade-size\) \* var\(--agent-edge-fade-top, 0\)\)[^}]*var\(--agent-canvas\) 0%[^}]*color-mix\(in srgb, var\(--agent-canvas\) 78%, transparent\) 46%[^}]*transparent 100%[^}]*opacity:\s*var\(--agent-edge-fade-top, 0\)/s);
    expect(transcript).toContain("useScrollEdgeState(scrollRef");
    expect(transcript).toContain("agentTranscriptFadeGeometry(scrollEdgeState.topFade)");
    expect(css).toMatch(/\.desktop-agent-dock-region\s*\{[^}]*padding:\s*var\(--agent-dock-padding-top\) var\(--agent-inline-inset\) var\(--agent-dock-padding-bottom\)/s);
    expect(css).toMatch(/\.desktop-agent-composer-shell\s*\{[^}]*padding:\s*0/s);
    expect(css).toMatch(/\.desktop-agent-composer-floating\s*\{[^}]*position:\s*absolute[^}]*bottom:\s*calc\(100% \+ 8px\)[^}]*pointer-events:\s*none/s);
    expect(css).toMatch(/--agent-sidebar-border:\s*var\(--po-divider\)/);
    expect(css).toMatch(/--agent-config-border:\s*var\(--po-border-subtle\)/);
    expect(css).toMatch(/--agent-row-hover-surface:\s*color-mix\(in srgb, var\(--po-hover\) 86%, transparent\)/);
    expect(css).toMatch(/--agent-row-selected-surface:\s*linear-gradient\(\s*90deg,\s*color-mix\(in srgb, var\(--po-selected\) 96%, transparent\) 0%,\s*color-mix\(in srgb, var\(--po-selected\) 88%, transparent\) calc\(100% - 36px\),\s*color-mix\(in srgb, var\(--po-selected\) 62%, transparent\) 100%\s*\)/s);
    expect(css).toMatch(/\.dark \.desktop-agent-boundary,[^{]*\{[^}]*--agent-row-hover-surface:\s*color-mix\(in srgb, rgba\(211, 208, 197, 0\.075\) 86%, transparent\)[^}]*--agent-row-selected-surface:\s*linear-gradient/s);
    expect(css).toMatch(/\.desktop-agent-composer\s*\{[^}]*padding:\s*0[^}]*border:\s*1px solid var\(--agent-border-subtle\)[^}]*border-radius:\s*var\(--agent-radius-composer\)[^}]*background:\s*var\(--agent-composer-surface\)/s);
    expect(css).not.toMatch(/\.desktop-agent-composer\s*\{[^}]*cursor:\s*text/s);
    expect(css).toMatch(/\.desktop-agent-composer\[data-input-disabled="true"\]\s*\{[^}]*cursor:\s*default/s);
    expect(css).toMatch(/\.desktop-agent-composer:hover:not\(\[data-input-disabled="true"\]\)\s*\{[^}]*border-color:\s*var\(--agent-border\)[^}]*background:\s*var\(--agent-composer-surface\)/s);
    expect(css).toMatch(/\.desktop-agent-composer:focus-within\s*\{[^}]*border-color:\s*var\(--agent-border\)[^}]*background:\s*var\(--agent-composer-surface\)/s);
    expect(css).not.toMatch(/\.desktop-agent-composer:(?:hover|focus-within)[^{]*\{[^}]*background:\s*var\(--agent-row-selected-surface\)/s);
    expect(picker).toContain("DesktopMenuItem");
    expect(menuCss).toMatch(/\.desktop-menu-item:hover:not\(:disabled\):not\(\[aria-disabled="true"\]\),[^{]*\.desktop-menu-item\.selected\s*\{[^}]*background:\s*var\(--po-hover\)/s);
    expect(css).not.toContain(".desktop-agent-picker-option.is-selected");
    expect(css).toMatch(/\.desktop-agent-composer-trailing\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1fr\) auto[^}]*min-height:\s*var\(--agent-composer-toolbar-height\)[^}]*padding:\s*0 8px 8px 12px[^}]*border:\s*0/s);
    expect(css).toMatch(/\.desktop-agent-picker-trigger\s*\{[^}]*width:\s*fit-content[^}]*border:\s*1px solid var\(--agent-config-border\)[^}]*background:\s*transparent/s);
    expect(css).toMatch(/\.desktop-agent-composer-picker\.is-model\s*\{[^}]*width:\s*max-content[^}]*max-width:\s*min\(148px, 34vw\)/s);
    expect(css).toMatch(/\.desktop-agent-composer-picker\.is-effort\s*\{[^}]*width:\s*max-content[^}]*max-width:\s*min\(72px, 20vw\)/s);
    expect(css).not.toContain("max-width: min(70%, 300px)");
    expect(css).toMatch(/--agent-composer-input-padding:\s*12px/);
    expect(css).not.toContain("--agent-composer-text-min-height");
    expect(css).toMatch(/--agent-composer-text-max-height:\s*120px/);
    expect(css).toMatch(/--agent-composer-input-min-height:\s*calc\(var\(--agent-composer-line-height\) \+ var\(--agent-composer-input-padding\) \+ var\(--agent-composer-input-padding\)\)/);
    expect(css).not.toMatch(/--agent-composer-input-min-height:\s*70px/);
    expect(css).toMatch(/--agent-composer-toolbar-height:\s*38px/);
    expect(css).toMatch(/--agent-composer-picker-padding-inline:\s*8px/);
    expect(css).toMatch(/\.desktop-agent-composer-row\s*\{[^}]*display:\s*flex[^}]*min-height:\s*var\(--agent-composer-input-min-height\)[^}]*flex-direction:\s*column[^}]*gap:\s*0/s);
    expect(css).toMatch(/\.desktop-agent-composer-input-row\s*\{[^}]*display:\s*grid[^}]*min-height:\s*var\(--agent-composer-input-min-height\)[^}]*grid-template-columns:\s*minmax\(0, 1fr\)[^}]*padding:\s*0/s);
    expect(css).toMatch(/\.desktop-agent-composer-actions\s*\{[^}]*display:\s*flex[^}]*margin-inline-start:\s*auto/s);
    expect(css).toMatch(/\.desktop-agent-picker-trigger\.is-compact\s*\{[^}]*width:\s*var\(--agent-control-size\)/s);
    expect(css).toMatch(/\.desktop-agent-composer-action\s*\{[^}]*width:\s*var\(--agent-control-size\)[^}]*height:\s*var\(--agent-control-size\)[^}]*border-radius:\s*50%/s);
    expect(css).toMatch(/--agent-composer-surface:\s*var\(--po-active\)/);
    expect(css).toMatch(/\.desktop-agent-composer-action:disabled\s*\{[^}]*background:\s*color-mix\(in srgb, var\(--agent-text\) 14%, transparent\)[^}]*color:\s*color-mix\(in srgb, var\(--agent-text\) 48%, transparent\)[^}]*opacity:\s*1/s);
    expect(composerToolbar).toContain('<ArrowUp size={17} strokeWidth={1.6} />');
    expect(attachmentButton).toContain('<Paperclip size={16} strokeWidth={1.7} aria-hidden="true" />');
    expect(attachmentButton).not.toContain("<Plus");
    expect(css).toMatch(/\.desktop-agent-prompt-editor \.cm-editor\s*\{[^}]*min-height:\s*var\(--agent-composer-input-min-height\)[^}]*max-height:\s*calc\(var\(--agent-composer-text-max-height\) \+ var\(--agent-composer-input-padding\) \+ var\(--agent-composer-input-padding\)\)[^}]*background:\s*transparent[^}]*font-size:\s*var\(--agent-font-size\)[^}]*line-height:\s*var\(--agent-composer-line-height\)/s);
    expect(css).toMatch(/\.desktop-agent-prompt-editor \.cm-content\s*\{[^}]*min-height:\s*var\(--agent-composer-input-min-height\)[^}]*padding:\s*var\(--agent-composer-input-padding\)[^}]*cursor:\s*text/s);
    expect(css).toMatch(/\.desktop-agent-composer-picker \.desktop-agent-picker-trigger\s*\{[^}]*padding-block:\s*0[^}]*padding-inline:\s*var\(--agent-composer-picker-padding-inline\)[^}]*border:\s*0[^}]*color:\s*var\(--agent-text-subtle\)[^}]*font-weight:\s*400/s);
    expect(css).not.toMatch(/\.desktop-agent-composer-picker\.is-effort \.desktop-agent-picker-trigger\s*\{[^}]*padding-inline-(?:start|end):/s);
    expect(css).toMatch(/\.desktop-agent-composer-picker \.desktop-agent-picker-trigger:focus-visible\s*\{[^}]*box-shadow:\s*inset 0 0 0 1px var\(--agent-border\)/s);
    expect(css).toMatch(/\.desktop-agent-session-menu\s*\{[^}]*inset-inline:\s*auto[^}]*inset-inline-start:\s*0/s);
    expect(transcript).not.toContain("What do you want to do in this project?");
    expect(transcript).not.toContain("What should we build?");
    expect(transcript).not.toContain("desktop-agent-empty");
    expect(panel).toContain("loading={startupLoading}");
    expect(panel).toContain("dock={startupLoading ? null");
    expect(panel).toContain("floatingAccessory=");
    expect(composerToolbar).toContain("<AgentAttachmentButton");
    expect(attachmentButton).toContain("inputRef.current?.click()");
    expect(attachmentButton).not.toContain("DesktopOverlayLayer");
    expect(attachmentButton).not.toContain('role="menu"');
    expect(css).toMatch(/\.desktop-agent-reference-trigger\s*\{[^}]*width:\s*var\(--agent-control-size\)[^}]*height:\s*var\(--agent-control-size\)/s);
    expect(css).toMatch(/--agent-reference-card-height:\s*52px/);
    expect(css).toMatch(/\.desktop-agent-reference-cards\s*\{[^}]*display:\s*flex[^}]*gap:\s*14px[^}]*padding:\s*12px 12px 0/s);
    expect(css).toMatch(/\.desktop-agent-reference-card\s*\{[^}]*height:\s*var\(--agent-reference-card-height\)[^}]*overflow:\s*visible[^}]*border-radius:\s*6px/s);
    expect(css).toMatch(/\.desktop-agent-reference-card\.is-file-card\s*\{[^}]*width:\s*min\(174px, 100%\)/s);
    expect(css).toMatch(/\.desktop-agent-reference-card\.is-image-card\s*\{[^}]*width:\s*var\(--agent-reference-card-height\)[^}]*flex:\s*0 0 var\(--agent-reference-card-height\)/s);
    expect(css).toMatch(/\.desktop-agent-reference-image-preview img\s*\{[^}]*object-fit:\s*cover/s);
    expect(css).toMatch(/\.desktop-agent-reference-card-actions\s*\{[^}]*inset-block-start:\s*-14px[^}]*inset-inline-end:\s*-14px/s);
    expect(css).toMatch(/\.desktop-agent-reference-card-actions > button\s*\{[^}]*width:\s*20px[^}]*height:\s*20px[^}]*background:\s*var\(--po-menu-bg\)/s);
    expect(css).toMatch(/\.desktop-agent-reference-card\.is-error\s*\{[^}]*border-color:\s*color-mix\(in srgb, var\(--po-danger\) 46%, var\(--agent-border-subtle\)\)/s);
    expect(composer.indexOf("<AgentDraftReferenceList")).toBeLessThan(composer.lastIndexOf("<AgentPromptEditor"));
    expect(composer.indexOf("<AgentDraftReferenceList")).toBeLessThan(composer.indexOf("<AgentComposerToolbar"));
    expect(composerToolbar).toContain('className="desktop-agent-composer-actions"');
    expect(composer).not.toContain("onMouseDown=");
    expect(composer).not.toContain("useAgentComposerFocus");
    expect(composerToolbar.indexOf('className="desktop-agent-composer-trailing"')).toBeLessThan(composerToolbar.indexOf("aria-label={primaryActionLabel}"));
    expect(composer).toContain("const primaryActionBusy = running ? stopping : submitting");
    expect(composer).toContain("const primaryActionDisabled = running ? stopping : !canSubmit");
    expect(composerToolbar).toContain('className={`desktop-agent-composer-action${running ? " is-stop" : ""}`}');
    expect(composer).toContain("onPrimaryAction={running ? onStop : () => void submit()}");
    expect(composerToolbar).toContain("onClick={onPrimaryAction}");
    expect(composer).not.toContain("{running && <button");
    expect(composer).not.toContain("{(!running || canSendWhileRunning)");
    expect(composer).not.toContain('className="desktop-agent-tools-menu"');
    expect(composer).not.toContain("AgentBackendPicker");
    expect(composer).not.toContain('is-backend');
    expect(composer).not.toContain("AgentProviderPicker");
    expect(composer).not.toContain("desktop-agent-composer-hint");
    expect(css).not.toContain(".desktop-agent-composer-hint");
    expect(panel).not.toContain("<AgentSurfaceHeader");
    expect(panel).not.toContain("<AgentRuntimePicker");
    expect(panel).toContain("t(DEFAULT_AGENT_COMPOSER_PLACEHOLDER_ID)");
    expect(composer).toContain('DEFAULT_AGENT_COMPOSER_PLACEHOLDER_ID = "agent.composer.placeholder.default"');
    expect(css).toMatch(/\.desktop-agent-picker\.is-header\s*\{[^}]*width:\s*max-content[^}]*max-width:\s*100%/s);
    expect(css).toMatch(/\.desktop-agent-picker\.is-header \.desktop-agent-picker-trigger\s*\{[^}]*width:\s*max-content[^}]*max-width:\s*100%[^}]*border:\s*0[^}]*font-size:\s*var\(--po-font-size-chrome, 13px\)[^}]*font-weight:\s*var\(--po-font-weight-chrome, 500\)/s);
    expect(css).not.toContain("max-width: min(68%, 300px)");
    expect(menuCss).toMatch(/\.desktop-menu-surface,[^{]*\{[^}]*border:\s*1px solid var\(--po-menu-border\)[^}]*border-radius:\s*var\(--po-menu-radius\)[^}]*background:\s*var\(--po-menu-bg\)[^}]*box-shadow:\s*var\(--po-menu-shadow\)/s);
    expect(menuCss).toMatch(/\.desktop-menu-surface\[data-menu-elevation="compact"\]\s*\{[^}]*box-shadow:\s*var\(--po-menu-shadow-compact\)/s);
    expect(css).toMatch(/\.desktop-agent-picker-popover\s*\{[^}]*opacity:\s*0[^}]*pointer-events:\s*none[^}]*visibility:\s*hidden/s);
    expect(css).not.toMatch(/\.desktop-agent-picker-popover\s*\{[^}]*(?:border|border-radius|background|box-shadow):/s);
    expect(css).toMatch(/\.desktop-agent-picker-popover\[data-positioned="true"\]\s*\{[^}]*opacity:\s*1[^}]*pointer-events:\s*auto[^}]*visibility:\s*visible/s);
    expect(css).not.toContain("desktop-agent-picker-in");
    expect(picker).toContain("DesktopMenuSection");
    expect(menuCss).toMatch(/\.desktop-menu-surface\[data-menu-tone="quiet"\] \.desktop-menu-section-label\s*\{[^}]*font-weight:\s*500[^}]*text-transform:\s*none/s);
    expect(menuCss).toMatch(/\.desktop-menu-surface\[data-menu-tone="quiet"\] \.desktop-menu-item,[^{]*\.desktop-menu-item-label,[^{]*\.desktop-menu-item-detail\s*\{[^}]*font-weight:\s*400/s);
    expect(tokensCss).toMatch(/--po-menu-item-height:\s*var\(--desktop-sidebar-row-height\)/);
    expect(tokensCss).toMatch(/--po-menu-item-radius:\s*var\(--desktop-control-radius\)/);
    expect(css).toMatch(/\.desktop-agent-session-header-actions\s*\{[^}]*border:\s*0[^}]*background:\s*transparent/s);
    expect(panelStatus).toContain("const detail = failed");
    expect(composer).not.toContain("<Zap");
    expect(panel).toContain('t("agent.composer.placeholder.followUp")');
    expect(panel).toContain("<AgentPanelLayout");
    expect(css).toMatch(/\.desktop-agent-jump-latest\s*\{[^}]*position:\s*absolute[^}]*inset-inline-start:\s*50%[^}]*width:\s*var\(--agent-control-size\)[^}]*height:\s*var\(--agent-control-size\)[^}]*border-radius:\s*50%[^}]*transform:\s*translateX\(-50%\)/s);
    expect(brandMark).toContain("const agents = RENDERER_ASSET_PATHS.icons.agents");
    expect(brandMark).toContain("resolveRendererPublicAssetUrl(agents.codexLight)");
    expect(brandMark).toContain("resolveRendererPublicAssetUrl(agents.claudeCode)");
    expect(brandMark).toContain("resolveRendererPublicAssetUrl(agents.cursor)");
    expect(brandMark).toContain("resolveRendererPublicAssetUrl(agents.opencode)");
    expect(brandMark).not.toMatch(/https?:\/\//);
  });

  it("uses the same quiet divider as the left sidebar edge", () => {
    expect(layoutCss).toMatch(/\.desktop-right-sidebar\s*\{[^}]*--desktop-right-sidebar-background:\s*var\(--po-header\)[^}]*--po-terminal-bg:\s*var\(--desktop-right-sidebar-background\)[^}]*overflow:\s*hidden[^}]*background:\s*var\(--desktop-right-sidebar-background\)/s);
    expect(layoutCss).toMatch(/\.desktop-right-sidebar:not\(\.is-open\)\s*\{[^}]*overflow:\s*visible/s);
    expect(layoutCss).toMatch(/\.desktop-right-sidebar-stack\s*\{[^}]*background:\s*var\(--desktop-right-sidebar-background\)/s);
    expect(layoutCss).toMatch(/\.desktop-right-sidebar-surface\s*\{[^}]*background:\s*var\(--desktop-right-sidebar-background\)/s);
    expect(css).toMatch(/\.desktop-right-sidebar \.desktop-agent-boundary\s*\{[^}]*--agent-canvas:\s*var\(--po-terminal-bg\)/s);
    expect(layoutCss).toMatch(/\.desktop-right-sidebar\.is-open\s*\{[^}]*border-inline-start-color:\s*var\(--po-sidebar-divider, var\(--po-divider\)\)/s);
    expect(layoutCss).not.toContain(".desktop-right-sidebar::before");
  });

  it("shares the Appearance typography scale with the left sidebar", () => {
    expect(css).toMatch(/--agent-font-size:\s*var\(--desktop-sidebar-font-size, var\(--po-text-size-sidebar, 13px\)\)/);
    expect(css).toMatch(/--agent-font-size-meta:\s*var\(--desktop-sidebar-font-size-meta, var\(--po-text-size-meta, 12px\)\)/);
    expect(css).toMatch(/\.desktop-agent-picker-trigger\s*\{[^}]*font-size:\s*var\(--agent-font-size\)/s);
    expect(css).toMatch(/\.desktop-agent-tool-name\s*\{[^}]*font-size:\s*var\(--agent-font-size\)/s);
    expect(css).toMatch(/\.desktop-agent-code-block pre\s*\{[^}]*font-size:\s*var\(--agent-code-font-size\)/s);
  });

  it("uses one centered product loader for startup without a duplicate status loader", () => {
    expect(transcript).toContain('import { PageLoading } from "../../../components/loading"');
    expect(transcript).toContain('className="desktop-agent-startup-loading"');
    expect(transcript).toContain("label={null}");
    expect(css).toMatch(/\.desktop-agent-startup-loading\s*\{[^}]*min-height:\s*100%[^}]*pointer-events:\s*none/s);
    expect(panel).not.toMatch(/hasStatus\s*=.*loading/);
    expect(panelStatus).not.toContain("LoaderCircle");
    expect(panelStatus).not.toContain("desktop-agent-provider-progress");
  });

  it("keeps native tool rows quiet until the user asks for detail", () => {
    expect(css).toMatch(/--agent-tool-foreground:\s*var\(--agent-text-subtle\)/);
    expect(css).toMatch(/\.desktop-agent-tool-icon\s*\{[^}]*display:\s*grid[^}]*color:\s*var\(--agent-tool-foreground\)/s);
    expect(css).toMatch(/\.desktop-agent-tool-name\s*\{[^}]*color:\s*var\(--agent-tool-foreground\)/s);
    expect(css).toMatch(/\.desktop-agent-tool-chevron\s*\{[^}]*grid-column:\s*3/s);
    expect(css).toMatch(/\.desktop-agent-tool-call\.has-detail \.desktop-agent-tool-summary\s*\{[^}]*grid-column:\s*4/s);
    expect(css).not.toContain("--agent-current-tool-accent");
    expect(css).toMatch(/\.desktop-agent-tool-name\s*\{[^}]*font-weight:\s*400/s);
    expect(css).not.toMatch(/\.desktop-agent-tool-(?:name|row)[^{]*(?:is-read|is-edit)\s*\{[^}]*(?:color|background):/s);
    expect(css).toMatch(/\.desktop-agent-tool-branch\s*\{[^}]*border:\s*0[^}]*border-inline-start:\s*2px solid var\(--agent-border-subtle\)[^}]*background:\s*transparent/s);
    expect(css).toMatch(/\.desktop-agent-tool-call\s*\{[^}]*margin:\s*0 4px var\(--agent-work-handoff-gap\)/s);
    expect(css).toMatch(/\.desktop-agent-tool-branch:has\(> \.desktop-agent-evidence-tree\)\s*\{[^}]*padding:\s*0[^}]*overflow:\s*clip[^}]*border:\s*0/s);
    expect(css).toMatch(/\.desktop-agent-evidence-tree\s*\{[^}]*font-family:\s*var\(--po-font-mono\)[^}]*font-size:\s*var\(--agent-font-size-meta\)[^}]*line-height:\s*1\.5/s);
    expect(css).toMatch(/\.desktop-agent-evidence-node::before\s*\{[^}]*border-inline-start:\s*1px solid var\(--agent-border-subtle\)[^}]*border-bottom:\s*1px solid var\(--agent-border-subtle\)/s);
    expect(css).toMatch(/\.desktop-agent-command-output,[^{]*\.desktop-agent-tool-output\s*\{[^}]*padding:\s*0[^}]*border:\s*0[^}]*color:\s*var\(--agent-text-subtle\)[^}]*font-size:\s*inherit/s);
    expect(evidenceTree).toContain('type AgentToolEvidenceNodeKind = "command" | "request" | "result"');
    expect(commandActivity).toContain('<AgentToolEvidenceNode kind="command" marker="$">');
    expect(commandActivity).toContain('<AgentToolEvidenceNode kind="result">');
    expect(commandActivity).not.toContain('"via Bash"');
    expect(commandActivity).not.toContain("commandMetadata");
    expect(commandActivity).not.toContain("CommandActions");
    expect(commandActivity).toContain("commandPresentationForActivity");
    expect(commandActivity).toContain("AgentToolTextEvidence");
    expect(fileQueryActivity).toContain("collectAgentToolResultLines");
    expect(evidenceModel).toContain("maxChars: 24 * 1024");
    expect(evidenceModel).toContain("maxLines: 400");
    expect(evidenceModel).toContain("maxLineChars: 4 * 1024");
    expect(fileQueryActivity).toContain("desktop-agent-search-results");
  });

  it("retains bounded overflow and explicit responsive contracts", () => {
    expect(css).toMatch(/\.desktop-agent-transcript\s*\{[^}]*overflow-x:\s*hidden/s);
    expect(css).not.toMatch(/@container desktop-agent \(max-width:\s*759px\)/);
    expect(css).toMatch(/@container desktop-agent \(max-width:\s*559px\)/);
    expect(css).toMatch(/@container desktop-agent \(max-width:\s*419px\)/);
    expect(css).toMatch(/\.desktop-agent-changes-pill\s*\{[^}]*min-height:\s*var\(--agent-control-size\)/s);
    expect(css).toMatch(/\.desktop-agent-tool-call\s*\{[^}]*margin:\s*0 4px var\(--agent-work-handoff-gap\)[^}]*padding:\s*0[^}]*border:\s*0[^}]*background:\s*transparent/s);
    expect(css).not.toContain(".desktop-agent-tool-call::before");
    expect(css).not.toContain("desktop-agent-research-pulse");
    expect(css).toMatch(/\.desktop-agent-command\s*\{[^}]*overflow:\s*visible[^}]*border:\s*0[^}]*border-radius:\s*6px/s);
    expect(css).not.toContain(".desktop-agent-tool-meta");
    expect(css).not.toContain(".desktop-agent-tool-action");
    expect(css).toMatch(/\.desktop-agent-context-divider\s*\{[^}]*grid-template-columns:\s*minmax\(18px, 1fr\) auto minmax\(18px, 1fr\)/s);
    expect(css).toMatch(/\.desktop-agent-picker-popover\s*\{[^}]*position:\s*fixed[^}]*top:\s*var\(--agent-overlay-top, 0px\)[^}]*left:\s*var\(--agent-overlay-left, 0px\)[^}]*z-index:\s*1300[^}]*width:\s*var\(--agent-overlay-width, 0px\)[^}]*max-height:\s*var\(--agent-overlay-max-height, 0px\)/s);
    expect(css).not.toContain("desktop-agent-picker-in");
    expect(css).not.toMatch(/\.desktop-agent-picker-popover\s*\{[^}]*animation:/s);
    expect(css).not.toMatch(/\.desktop-agent-picker-trigger\[aria-expanded="true"\]/);
    expect(css).not.toMatch(/\.desktop-agent-picker-popover\s*\{[^}]*backdrop-filter:/s);
    expect(picker).toContain("DesktopOverlayLayer");
    expect(picker).toContain('boundarySelector: ".desktop-agent-boundary"');
  });

  it("keeps fenced results compact and makes Copy a quiet icon action", () => {
    expect(safeMarkdown).toContain('className="desktop-agent-code-copy"');
    expect(safeMarkdown).toContain("aria-label={copyLabel}");
    expect(safeMarkdown).toContain('data-language={language || "text"}');
    expect(safeMarkdown).not.toContain("<span>{language || \"text\"}</span>");
    expect(css).toMatch(/\.desktop-agent-code-block\s*\{[^}]*position:\s*relative[^}]*margin:\s*10px 0[^}]*border-radius:\s*10px/s);
    expect(css).toMatch(/\.desktop-agent-code-copy\s*\{[^}]*position:\s*absolute[^}]*width:\s*26px[^}]*height:\s*26px[^}]*background:\s*transparent[^}]*color:\s*var\(--agent-text-subtle\)/s);
    expect(css).toMatch(/\.desktop-agent-code-block pre\s*\{[^}]*padding:\s*9px 38px 9px 12px[^}]*color:\s*var\(--agent-text-muted\)[^}]*line-height:\s*1\.5/s);
  });

  it("renders file mentions as quiet accent-colored atomic references without a drag overlay", () => {
    expect(css).toMatch(/\.desktop-agent-prompt-mention\s*\{[^}]*display:\s*inline-flex[^}]*border:\s*1px solid color-mix\(in srgb, var\(--agent-accent\) 36%, var\(--agent-border-subtle\)\)[^}]*background:\s*color-mix\(in srgb, var\(--agent-accent-soft\) 58%, transparent\)[^}]*color:\s*color-mix\(in srgb, var\(--agent-accent\) 78%, var\(--agent-text\)\)/s);
    expect(css).not.toContain(".desktop-agent-reference-drop-overlay");
    expect(css).not.toContain('[data-drop-active="true"]');
  });
});
