import type { FileIconThemeId, Workspace } from "@puppyone/shared-ui";
import type { DesktopCloudSession } from "../../lib/cloudApi";
import type { DesktopUpdateState, GitStatusSnapshot, PuppyoneWorkspaceConfig } from "../../types/electron";
import type { DarkThemePreset, DiffMarkers, DockIcon, ExperimentalSettings, ExternalAppsSettings, FilesVisibilitySettings, LightThemePreset, LoadingAnimationPreset, RightSidebarToolsSettings, SidebarNavigationLayout, SidebarNavigationVisibilitySettings, TextSize, ThemeMode, TitlebarActionsSettings, TypographyPreferences } from "../../preferences";

export type SettingsSection = "workspace" | "language" | "appearance" | "external-apps" | "editor" | "experimental" | "git" | "files" | "account" | "cloud";

export type SettingsViewProps = {
  workspace: Workspace;
  activeSection: SettingsSection;
  gitStatus: GitStatusSnapshot | null;
  gitStatusLoading: boolean;
  gitStatusError: string | null;
  themeMode: ThemeMode;
  lightThemePreset: LightThemePreset;
  darkThemePreset: DarkThemePreset;
  loadingAnimationPreset: LoadingAnimationPreset;
  textSize: TextSize;
  typographyPreferences: TypographyPreferences;
  pointerCursors: boolean;
  dockIcon: DockIcon;
  diffMarkers: DiffMarkers;
  fileIconTheme: FileIconThemeId;
  sidebarNavigationLayout: SidebarNavigationLayout;
  sidebarNavigationVisibilitySettings: SidebarNavigationVisibilitySettings;
  filesVisibilitySettings: FilesVisibilitySettings;
  externalAppsSettings: ExternalAppsSettings;
  experimentalSettings: ExperimentalSettings;
  rightSidebarToolsSettings: RightSidebarToolsSettings;
  titlebarActionsSettings: TitlebarActionsSettings;
  aiEditAssistEnabled: boolean;
  cloudEnabled: boolean;
  cloudSession: DesktopCloudSession | null;
  cloudSessionRestoring: boolean;
  cloudApiBaseUrl: string | null;
  puppyoneConfig: PuppyoneWorkspaceConfig | null;
  puppyoneConfigLoading: boolean;
  puppyoneConfigSaving: boolean;
  puppyoneConfigError: string | null;
  updateState: DesktopUpdateState;
  onThemeModeChange: (mode: ThemeMode) => void;
  onLightThemePresetChange: (preset: LightThemePreset) => void;
  onDarkThemePresetChange: (preset: DarkThemePreset) => void;
  onLoadingAnimationPresetChange: (preset: LoadingAnimationPreset) => void;
  onTextSizeChange: (textSize: TextSize) => void;
  onTypographyPreferencesChange: (preferences: TypographyPreferences) => void;
  onPointerCursorsChange: (enabled: boolean) => void;
  onDockIconChange: (icon: DockIcon) => void;
  onDiffMarkersChange: (markers: DiffMarkers) => void;
  onFileIconThemeChange: (theme: FileIconThemeId) => void;
  onSidebarNavigationLayoutChange: (layout: SidebarNavigationLayout) => void;
  onSidebarNavigationVisibilitySettingsChange: (settings: SidebarNavigationVisibilitySettings) => void;
  onFilesVisibilitySettingsChange: (settings: FilesVisibilitySettings) => void;
  onExternalAppsSettingsChange: (settings: ExternalAppsSettings) => void;
  onExperimentalSettingsChange: (settings: ExperimentalSettings) => void;
  onRightSidebarToolsSettingsChange: (settings: RightSidebarToolsSettings) => void;
  onTitlebarActionsSettingsChange: (settings: TitlebarActionsSettings) => void;
  onAiEditAssistEnabledChange: (enabled: boolean) => void;
  onCloudSessionChange: (session: DesktopCloudSession | null) => void;
  onPuppyoneConfigChange: (config: PuppyoneWorkspaceConfig) => Promise<PuppyoneWorkspaceConfig | null>;
  onUnlinkWorkspace: () => Promise<void>;
  onRefreshGitStatus: () => void;
  onCheckForUpdates: () => void;
  onUpdateNow: () => void;
};

export type SettingsSidebarProps = {
  activeSection: SettingsSection;
  onSelectSection: (section: SettingsSection) => void;
};
