import type { FileIconThemeId, Workspace } from "@puppyone/shared-ui";
import type { DesktopCloudSession } from "../../lib/cloudApi";
import type { DesktopUpdateState, GitStatusSnapshot, PuppyoneWorkspaceConfig } from "../../types/electron";
import type { CreateNewMenuSettings, DarkThemePreset, ExperimentalSettings, FilesVisibilitySettings, GitSidebarLayout, InterfaceStyle, LightThemePreset, LoadingAnimationPreset, LocalAgentsSettings, RightSidebarToolsSettings, SidebarNavigationLayout, SidebarNavigationVisibilitySettings, TextSize, ThemeMode, TitlebarActionsSettings, TypographyPreferences } from "../../preferences";
import type { ResolvedAppearance } from "../appearance/resolveAppearance";
import type { SubThemeCatalogController } from "../themes/useSubThemeCatalog";

export type SettingsSection = "general" | "privacy" | "local-project" | "appearance" | "local-agents" | "editor" | "new-menu" | "experimental" | "git" | "files" | "account" | "cloud";

export type SettingsViewProps = {
  workspace: Workspace;
  activeSection: SettingsSection;
  gitStatus: GitStatusSnapshot | null;
  gitStatusLoading: boolean;
  gitStatusError: string | null;
  themeMode: ThemeMode;
  interfaceStyle: InterfaceStyle;
  resolvedAppearance: ResolvedAppearance;
  lightThemePreset: LightThemePreset;
  darkThemePreset: DarkThemePreset;
  loadingAnimationPreset: LoadingAnimationPreset;
  localAgentsSettings: LocalAgentsSettings;
  textSize: TextSize;
  typographyPreferences: TypographyPreferences;
  pointerCursors: boolean;
  requestedSubThemeId: string;
  subThemeCatalog: SubThemeCatalogController;
  fileIconTheme: FileIconThemeId;
  sidebarNavigationLayout: SidebarNavigationLayout;
  sidebarNavigationVisibilitySettings: SidebarNavigationVisibilitySettings;
  filesVisibilitySettings: FilesVisibilitySettings;
  createNewMenuSettings: CreateNewMenuSettings;
  experimentalSettings: ExperimentalSettings;
  rightSidebarToolsSettings: RightSidebarToolsSettings;
  titlebarActionsSettings: TitlebarActionsSettings;
  gitSidebarLayout: GitSidebarLayout;
  cloudEnabled: boolean;
  cloudSession: DesktopCloudSession | null;
  cloudSessionRestoring: boolean;
  cloudApiBaseUrl: string | null;
  puppyoneConfig: PuppyoneWorkspaceConfig | null;
  puppyoneConfigLoading: boolean;
  puppyoneConfigSaving: boolean;
  puppyoneConfigError: string | null;
  updateState: DesktopUpdateState;
  onThemeModeChange: (mode: ThemeMode) => void;
  onInterfaceStyleChange: (style: InterfaceStyle) => void;
  onLoadingAnimationPresetChange: (preset: LoadingAnimationPreset) => void;
  onLocalAgentsSettingsChange: (settings: LocalAgentsSettings) => void;
  onAgentFileActivityIndicatorsEnabledChange: (enabled: boolean) => void;
  onTextSizeChange: (textSize: TextSize) => void;
  onTypographyPreferencesChange: (preferences: TypographyPreferences) => void;
  onPointerCursorsChange: (enabled: boolean) => void;
  onSubThemeChange: (subThemeId: string) => void;
  onFileIconThemeChange: (theme: FileIconThemeId) => void;
  onSidebarNavigationLayoutChange: (layout: SidebarNavigationLayout) => void;
  onSidebarNavigationVisibilitySettingsChange: (settings: SidebarNavigationVisibilitySettings) => void;
  onFilesVisibilitySettingsChange: (settings: FilesVisibilitySettings) => void;
  onCreateNewMenuSettingsChange: (settings: CreateNewMenuSettings) => void;
  onExperimentalSettingsChange: (settings: ExperimentalSettings) => void;
  onRightSidebarToolsSettingsChange: (settings: RightSidebarToolsSettings) => void;
  onTitlebarActionsSettingsChange: (settings: TitlebarActionsSettings) => void;
  onGitSidebarLayoutChange: (layout: GitSidebarLayout) => void;
  onCloudSessionChange: (session: DesktopCloudSession | null) => void;
  onPuppyoneConfigChange: (config: PuppyoneWorkspaceConfig) => Promise<PuppyoneWorkspaceConfig | null>;
  onUnlinkWorkspace: () => Promise<void>;
  onRefreshGitStatus: () => void;
  onCheckForUpdates: () => void;
  onUpdateNow: () => void;
};

export type SettingsSidebarProps = {
  activeSection: SettingsSection;
  cloudEnabled: boolean;
  onSelectSection: (section: SettingsSection) => void;
};
