import type { FileIconThemeId, Workspace } from "@puppyone/shared-ui";
import type { DesktopCloudSession } from "../../lib/cloudApi";
import type { DesktopUpdateState, GitStatusSnapshot, PuppyoneWorkspaceConfig } from "../../types/electron";
import type { CreateNewMenuSettings, DarkThemePreset, DiffMarkers, DockIcon, ExperimentalSettings, ExternalAppsSettings, FilesVisibilitySettings, GitSidebarLayout, InterfaceStyle, LightThemePreset, LoadingAnimationPreset, LocalAgentsSettings, RightSidebarToolsSettings, SidebarNavigationLayout, SidebarNavigationVisibilitySettings, TerminalSessionLayout, TextSize, ThemeMode, TitlebarActionsSettings, TypographyPreferences } from "../../preferences";
import type { ResolvedAppearance } from "../appearance/resolveAppearance";
import type { EditorPresentation } from "../appearance/interfaceStyles";

export type SettingsSection = "general" | "local-project" | "appearance" | "local-agents" | "external-apps" | "editor" | "new-menu" | "experimental" | "git" | "files" | "account" | "cloud";

export type SettingsViewProps = {
  workspace: Workspace;
  activeSection: SettingsSection;
  gitStatus: GitStatusSnapshot | null;
  gitStatusLoading: boolean;
  gitStatusError: string | null;
  themeMode: ThemeMode;
  interfaceStyle: InterfaceStyle;
  resolvedAppearance: ResolvedAppearance;
  lightThemePreset: LightThemePreset;
  darkThemePreset: DarkThemePreset;
  loadingAnimationPreset: LoadingAnimationPreset;
  localAgentsSettings: LocalAgentsSettings;
  agentFileActivityIndicatorsEnabled: boolean;
  textSize: TextSize;
  typographyPreferences: TypographyPreferences;
  pointerCursors: boolean;
  dockIcon: DockIcon;
  diffMarkers: DiffMarkers;
  fileIconTheme: FileIconThemeId;
  sidebarNavigationLayout: SidebarNavigationLayout;
  sidebarNavigationVisibilitySettings: SidebarNavigationVisibilitySettings;
  filesVisibilitySettings: FilesVisibilitySettings;
  externalAppsSettings: ExternalAppsSettings;
  createNewMenuSettings: CreateNewMenuSettings;
  experimentalSettings: ExperimentalSettings;
  rightSidebarToolsSettings: RightSidebarToolsSettings;
  titlebarActionsSettings: TitlebarActionsSettings;
  terminalSessionLayout: TerminalSessionLayout;
  gitSidebarLayout: GitSidebarLayout;
  aiEditAssistEnabled: boolean;
  cloudEnabled: boolean;
  cloudSession: DesktopCloudSession | null;
  cloudSessionRestoring: boolean;
  cloudApiBaseUrl: string | null;
  puppyoneConfig: PuppyoneWorkspaceConfig | null;
  puppyoneConfigLoading: boolean;
  puppyoneConfigSaving: boolean;
  puppyoneConfigError: string | null;
  updateState: DesktopUpdateState;
  onThemeModeChange: (mode: ThemeMode) => void;
  onInterfaceStyleChange: (style: InterfaceStyle) => void;
  onEditorPresentationChange: (presentation: EditorPresentation) => void;
  onLightThemePresetChange: (preset: LightThemePreset) => void;
  onDarkThemePresetChange: (preset: DarkThemePreset) => void;
  onLoadingAnimationPresetChange: (preset: LoadingAnimationPreset) => void;
  onLocalAgentsSettingsChange: (settings: LocalAgentsSettings) => void;
  onAgentFileActivityIndicatorsEnabledChange: (enabled: boolean) => void;
  onTextSizeChange: (textSize: TextSize) => void;
  onTypographyPreferencesChange: (preferences: TypographyPreferences) => void;
  onPointerCursorsChange: (enabled: boolean) => void;
  onDockIconChange: (icon: DockIcon) => void;
  onDiffMarkersChange: (markers: DiffMarkers) => void;
  onFileIconThemeChange: (theme: FileIconThemeId) => void;
  onSidebarNavigationLayoutChange: (layout: SidebarNavigationLayout) => void;
  onSidebarNavigationVisibilitySettingsChange: (settings: SidebarNavigationVisibilitySettings) => void;
  onFilesVisibilitySettingsChange: (settings: FilesVisibilitySettings) => void;
  onExternalAppsSettingsChange: (settings: ExternalAppsSettings) => void;
  onCreateNewMenuSettingsChange: (settings: CreateNewMenuSettings) => void;
  onExperimentalSettingsChange: (settings: ExperimentalSettings) => void;
  onRightSidebarToolsSettingsChange: (settings: RightSidebarToolsSettings) => void;
  onTitlebarActionsSettingsChange: (settings: TitlebarActionsSettings) => void;
  onTerminalSessionLayoutChange: (layout: TerminalSessionLayout) => void;
  onGitSidebarLayoutChange: (layout: GitSidebarLayout) => void;
  onAiEditAssistEnabledChange: (enabled: boolean) => void;
  onCloudSessionChange: (session: DesktopCloudSession | null) => void;
  onPuppyoneConfigChange: (config: PuppyoneWorkspaceConfig) => Promise<PuppyoneWorkspaceConfig | null>;
  onUnlinkWorkspace: () => Promise<void>;
  onRefreshGitStatus: () => void;
  onCheckForUpdates: () => void;
  onUpdateNow: () => void;
};

export type SettingsSidebarProps = {
  activeSection: SettingsSection;
  onSelectSection: (section: SettingsSection) => void;
};
