/* This file is generated by scripts/generate-interface-styles.mjs. */

export const INTERFACE_STYLE_MANIFEST = {
  "version": 1,
  "defaultStyle": "default",
  "storage": {
    "interfaceStyle": "puppyone.desktop.interfaceStyle",
    "themeMode": "puppyone.desktop.theme"
  },
  "styles": [
    {
      "id": "default",
      "labelKey": "settings.appearance.interfaceStyle.default",
      "palette": {
        "kind": "adaptive",
        "modes": [
          "system",
          "light",
          "dark"
        ],
        "fallbackMode": "system",
        "presetControls": {
          "light": true,
          "dark": true
        }
      },
      "firstPaint": {
        "light": {
          "background": "#f1eadf",
          "colorScheme": "light"
        },
        "dark": {
          "background": "#0e0e0e",
          "colorScheme": "dark"
        }
      },
      "stylesheet": null
    },
    {
      "id": "windows-xp",
      "labelKey": "settings.appearance.interfaceStyle.windowsXp",
      "palette": {
        "kind": "fixed",
        "mode": "light"
      },
      "firstPaint": {
        "light": {
          "background": "#dfe9f5",
          "colorScheme": "light"
        }
      },
      "stylesheet": "windows-xp.css"
    },
    {
      "id": "macos-tiger",
      "labelKey": "settings.appearance.interfaceStyle.macosTiger",
      "palette": {
        "kind": "fixed",
        "mode": "light"
      },
      "firstPaint": {
        "light": {
          "background": "#d7d7d7",
          "colorScheme": "light"
        }
      },
      "stylesheet": "macos-tiger.css"
    }
  ]
} as const;
